import { create } from 'zustand';

export interface Note {
  id: string;
  title: string;
  content: string; // Markdown supported
  category: string;
  tags: string[];
  favorite: boolean;
  aiSummary?: string;
  createdAt: string;
  updatedAt: string;
}

interface NoteState {
  notes: Note[];
  activeNoteId: string | null;
  addNote: (note: Omit<Note, 'id' | 'createdAt' | 'updatedAt'>) => string;
  updateNote: (id: string, updates: Partial<Note>) => void;
  deleteNote: (id: string) => void;
  toggleFavorite: (id: string) => void;
  setActiveNoteId: (id: string | null) => void;
  summarizeNoteWithAi: (id: string) => Promise<void>;
  suggestTagsWithAi: (id: string) => Promise<void>;
}

const initialNotes: Note[] = [
  {
    id: 'n-1',
    title: '🧠 Second Brain Concept & Notes',
    content: `# LifeOS Second Brain Setup\n\nA central repository for all my thoughts, code snippets, configurations, and plans. Keeping this updated helps offload raw memory storage from the physical brain.\n\n## Core Pillars\n- **Projects**: Direct actionable deliverables.\n- **Areas**: Responsibilities that require ongoing standard.\n- **Resources**: Reference libraries and documents.\n- **Archives**: Inactive items from the previous three folders.\n\n## Action Plan\n- Integrate AI assistance directly into note tags.\n- Implement auto-linking of skills to notes.`,
    category: 'Productivity',
    tags: ['Mindset', 'SaaS', 'Workflow'],
    favorite: true,
    aiSummary: "Explores the framework of 'Second Brain' based on PARA methodology, detailing action plans for tag integration and note linking.",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'n-2',
    title: '🌐 Tailwind CSS v4 Reference Sheet',
    content: `# Tailwind v4 Directives\n\nTailwind v4 is css-first. No tailwind.config.js is generated by default.\n\n### Custom Theme\n\`\`\`css\n@import "tailwindcss";\n\n@theme {\n  --color-primary: #00FF88;\n}\n\`\`\`\n\n### Benefits\n- Super fast build times via Rust compiler.\n- Standard native CSS variables syntax.`,
    category: 'Learning',
    tags: ['Tailwind', 'CSS', 'Vite'],
    favorite: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const useNoteStore = create<NoteState>((set) => ({
  notes: initialNotes,
  activeNoteId: 'n-1',

  addNote: (noteData) => {
    const newId = 'n-' + Math.random().toString(36).substr(2, 9);
    set((state) => {
      const newNote: Note = {
        ...noteData,
        id: newId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      return { 
        notes: [newNote, ...state.notes],
        activeNoteId: newId
      };
    });
    return newId;
  },

  updateNote: (id, updates) => set((state) => ({
    notes: state.notes.map((note) =>
      note.id === id
        ? { ...note, ...updates, updatedAt: new Date().toISOString() }
        : note
    )
  })),

  deleteNote: (id) => set((state) => {
    const updatedNotes = state.notes.filter((note) => note.id !== id);
    const newActiveId = state.activeNoteId === id
      ? (updatedNotes.length > 0 ? updatedNotes[0].id : null)
      : state.activeNoteId;
    return {
      notes: updatedNotes,
      activeNoteId: newActiveId
    };
  }),

  toggleFavorite: (id) => set((state) => ({
    notes: state.notes.map((note) =>
      note.id === id ? { ...note, favorite: !note.favorite } : note
    )
  })),

  setActiveNoteId: (id) => set({ activeNoteId: id }),

  summarizeNoteWithAi: async (id) => {
    await new Promise((resolve) => setTimeout(resolve, 1200));
    set((state) => ({
      notes: state.notes.map((note) => {
        if (note.id !== id) return note;
        const text = note.content.substring(0, 100).replace(/[#\*\_]/g, '');
        const summary = `🤖 [AI Summarizer]: The note focuses on "${note.title}" discussing details around ${text}... and establishing next steps.`;
        return { ...note, aiSummary: summary };
      })
    }));
  },

  suggestTagsWithAi: async (id) => {
    await new Promise((resolve) => setTimeout(resolve, 1000));
    set((state) => ({
      notes: state.notes.map((note) => {
        if (note.id !== id) return note;
        const contentLower = note.content.toLowerCase();
        const newTags = [...note.tags];
        if (contentLower.includes('css') && !newTags.includes('Design')) newTags.push('Design');
        if (contentLower.includes('para') && !newTags.includes('PARA')) newTags.push('PARA');
        if (contentLower.includes('build') && !newTags.includes('Dev')) newTags.push('Dev');
        return { ...note, tags: newTags };
      })
    }));
  }
}));
